### ISSUE TITLE
File input in `sd:layout advanced: true` causes error in web interface

### ISSUE THREAD

**Issue by heylel-b-sh** [datirium/workflows#40]
Looks like uncommenting `sd:layout` causes error `Input type "file" isn't supported by matInput` when displaying the workflow. Bug can be tested on [rgt-thor.cwl](https://github.com/datirium/workflows/blob/master/workflows/rgt-thor.cwl) workflow

Workflow input example
```yaml
housekeeping_genes_bed_file:
  type: File?
  format: "http://edamontology.org/format_3003"
  label: "Housekeeping genes file"
  doc: "Define housekeeping genes (BED format) used for normalizing"
  # 'sd:layout':
  #   advanced: true
```
