### ISSUE TITLE
bigWig track is not displayed when output if File[] or some other reason?

### ISSUE THREAD

**Issue by heylel-b-sh** [datirium/workflows#41]
Use [rgt-thor.cwl](https://github.com/datirium/workflows/blob/master/workflows/rgt-thor.cwl) as an example.
The following output is not displayed in IGV
```yaml
  cond_1_bigwig_file:
    type: File[]
    format: "http://edamontology.org/format_3006"
    label: "First biological condition ChIP-seq signals"
    doc: "Postprocessed ChIP-seq signals from the first biological condition samples"
    outputSource: thor/cond_1_bigwig_file
    'sd:visualPlugins':
    - igvbrowser:
        tab: 'IGV Genome Browser'
        id: 'igvbrowser'
        type: 'wig'
        name: "Biological condition 1"
        height: 120
```
